spring:
  mvc:
    #所有的访问都经过静态资源路径
    static-path-pattern: /**
  thymeleaf:
    #thymelea模板配置
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    encoding: UTF-8
    servlet:
      content-type: text/html
    #热部署文件，页面不产生缓存，及时更新
    cache: false
    resources:
      #指定静态资源根路径
      static-locations: classpath:/static/
      chain:
        strategy:
          content:
            enabled: true
            paths: /**
