#hibernate相关配置
hibernate:
  dialect: org.hibernate.dialect.MySQL5Dialect
  show_sql: true
  format_sql: true
  use_sql_comments: true
  max_fetch_depth: 1
  generate_statistics: false
  current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
  jdbc:
    batch_size: 300
  cache:
    use_second_level_cache: false
    provider_class: net.sf.ehcache.hibernate.EhCacheProvider
    region:
      factory_class: org.hibernate.cache.ehcache.EhCacheRegionFactory
  hbm2ddl:
    auto: update
  search:
    indexBase: c:/index
    directory_provider: filesystem
    batch_size: 1000
    analyzer: org.apache.lucene.analysis.cjk.CJKAnalyzer
    indexing_strategy: manual
#spring相关配置
spring:
  #redis缓存的配置
  cache:
    type: redis
  redis:
    host: localhost
    port: 6379
    password: 123456
    database: 0
    timeout: 1800000ms
    jedis:
      pool:
        max-active: 8
        max-wait: -1ms
        max-idle: 8
        min-idle: 0
  #rabbit的配置http://localhost:15672
  rabbitmq:
    host: 0.0.0.0
    port: 5672
    username: admin
    password: admin
    virtual-host: /
    connection-timeout: 30000ms
    publisher-confirms: false
    template:
      exchange: EX_DEFAULT
      routing-key: RK_DEFAULT
    cache:
      connection:
        mode: connection
      channel:
        size: 50
        checkout-timeout: 10000ms
  #mongodb
  data:
    mongodb:
      uri: mongodb://localhost:27017/test
      username: test
      password: test

