server:
  port: 8001

spring:
  application:
    name: business-service

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

#打开feign对hustrix的支持,否则fallback不生效
feign:
  hystrix:
    enabled: true